### ISSUE TITLE
How to visualize the output?

### ISSUE THREAD

**Issue by ksalihcavusoglu** [nikk-nikaznan/SSVEP-Neural-Generative-Models#1]
Thank you for your effort. I have run the solution and generated fake_class0.py. How can i visualize the output? Can you commit sample code?

**Comment by nikk-nikaznan** [comment]
Hi there. Sorry for the delay response. I use Fast Fourier Transform (FFT) to visualise my signals. I added the sample code in the repo now. Thank you.
