### ISSUE TITLE
Regarding the input data shape

### ISSUE THREAD

**Issue by vpKumaravel** [nikk-nikaznan/SSVEP-Neural-Generative-Models#2]
Hi,

Thanks for this useful work and for sharing the code. 
I am trying to run your model feeding the SSVEP data I have. In your example, I noticed the input data is of [10, 2, 1500]. Could you please explain what each of these values represents? 

Thanks,
Velu

**Comment by nikk-nikaznan** [comment]
Hi, these values represent [the batch size, the number of channels for the sensor used, the number of samples]

**Comment by vpKumaravel** [comment]
Thanks a lot!
